name: Deploy Node.js App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci
        working-directory: testapp

      - name: Build
        run: npm run build
        working-directory: testapp

      - name: Archive build artifacts
        run: tar -cvf build.tar package.json package-lock.json -C dist .
        working-directory: testapp

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: testapp/build.tar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build

      - name: Display environment variables
        run: echo ${{ vars }}

      - name: Copy file via scp
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "build.tar"
          target: "/var/meeploy/apps/testserver"

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/meeploy/apps/testserver
            tar -xvf build.tar
            npm install --production
            pm2 restart /var/meeploy/pm2.config.json --only testserver --env="${{ toJson(vars) }}"
